# Generated by Django 4.2 on 2023-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
