# Generated by Django 4.2 on 2023-05-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
